spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: false
#
#  data:
#    mongodb:
#      uri: ${MONGODB_URI}

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_URL}

logging:
  level:
    root: INFO
    org.springframework.security: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

#mail:
#  host: ${SMTP_HOST}
#  port: ${SMTP_PORT}
#  username: ${SMTP_USERNAME}
#  password: ${SMTP_PASSWORD}
